# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    registry_manager:
        class: AppBundle\Registry\RegistryManager
        arguments: ['@logger', '%registry_baseuri%']
        tags:
            - { name: monolog.logger, channel: registry }
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
